[package]
name = "mcas"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.17.8"
#colored = "2"
reqwest = { version = "0.12.2", features = ["blocking"] }
