[package]
name = "mcas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
concat-string = "1.0.1"
indicatif = "0.17.8"
reqwest = { version = "0.12.2", features = ["blocking", "stream"] }
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3.30"
